### ISSUE TITLE
不知道作者有没有用过Glide

### ISSUE THREAD

**Issue by vecharm** [listenzz/AndroidNavigation#12]
java.lang.ClassCastException: com.bumptech.glide.manager.SupportRequestManagerFragment cannot be cast to me.listenzz.navigation.AwesomeFragment
                                                  at me.listenzz.navigation.AwesomeFragment.getChildFragmentsAtAddedList(AwesomeFragment.java:405)
                                                  at me.listenzz.navigation.AwesomeFragment.onHiddenChanged(AwesomeFragment.java:177)
                                                  at me.listenzz.navigation.AwesomeFragment.onHiddenChanged(AwesomeFragment.java:179)
                                                  at android.support.v4.app.FragmentManagerImpl.completeShowHideFragment(FragmentManager.java:1719)
                                                  at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1778)
                                                  at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:794)
                                                  at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
                                                  at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
                                                  at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
                                                  at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
                                                  at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
                                                  at android.os.Handler.handleCallback(Handler.java:815)
                                                  at android.os.Handler.dispatchMessage(Handler.java:104)
                                                  at android.os.Looper.loop(Looper.java:194)
                                                  at android.app.ActivityThread.main(ActivityThread.java:5868)
                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1019)
                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:814)

**Comment by listenzz** [comment]
感谢反馈，我们项目有一个地方使用了 glide

该问题已经修复，谢谢。

**Comment by listenzz** [comment]
此 issue 太久没有活跃，因此关闭
